# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provision "shell", path: "scripts/install-bcc.sh"
end
